spring.application.name=scm2.0

server.port=8082

# ✅ Disable Thymeleaf caching
spring.thymeleaf.cache=false

# ✅ (Optional but recommended for live reload)
spring.devtools.restart.enabled=true

# ✅ (Optional if using livereload browser extension)
spring.devtools.livereload.enabled=true


# Postgres database configuration

# Data source url 
# spring.datasource.url=jdbc:Postgres://localhost:5432/scm20
spring.datasource.url=jdbc:postgresql://localhost:5432/scm20
spring.datasource.username=postgres
spring.datasource.password=root

# jpa configuration
spring.jpa.show-sql=true

# For creating schemas and table
spring.jpa.hibernate.ddl-auto=update

# If below is not write then also it will auto configure
# spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# We can format the sql if required using below line
spring.jpa.properties.hibernate.format_sql= true;
 


# Email configuration

# security configuration

# spring.security.user.name=sakib
# spring.security.user.password=sakib@123

# Oauth2 client configuration
# google configure
spring.security.oauth2.client.registration.google.client-id= 107717548513-j4tfa4modhgtk6b79fuc96r3a00bp4pn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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
spring.security.oauth2.client.registration.google.scope= email,profile

# github configure 
spring.security.oauth2.client.registration.github.client-id= Iv23liZOI8UMUaFTgIFv
spring.security.oauth2.client.registration.github.client-secret= 1352584b5d9dad37301a08a31df3a20466d1f49e
spring.security.oauth2.client.registration.github.scope= email,profile

# cloudinary property
cloudinary.cloud.name=dmayhyh2m
cloudinary.api.key=859788233619675
cloudinary.api_secret=XGfFxR_09yg2WRXg7jN85iiBeTg

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# spring.profiles.active=dev
