# google configuration
spring.security.oauth2.client.registration.google.client-id= 107717548513-j4tfa4modhgtk6b79fuc96r3a00bp4pn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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
spring.security.oauth2.client.registration.google.scope= email,profile

# github configure 
spring.security.oauth2.client.registration.github.client-id= Iv23liZOI8UMUaFTgIFv
spring.security.oauth2.client.registration.github.client-secret= 1352584b5d9dad37301a08a31df3a20466d1f49e
spring.security.oauth2.client.registration.github.scope= email,profile
